---
# tasks file for /etc/ansible/roles/nginx_lb
- name: Configure nginx LB conf file
  template:
    src: lb.conf.j2
    dest: /etc/nginx/conf.d/lb.conf

- name: Restart nginx
  service: 
    name: nginx
    state: restarted
